// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVGvHxYZRcSSpo3hamuUy76KGPtGWTOaQ',
    appId: '1:482880286924:web:16864cf1b0d4e91e8c5269',
    messagingSenderId: '482880286924',
    projectId: 'truemedic-ef04a',
    authDomain: 'truemedic-ef04a.firebaseapp.com',
    storageBucket: 'truemedic-ef04a.firebasestorage.app',
    measurementId: 'G-50GJ3HV4EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMgoA41LRyt25cAurMeyBNMrVMc67O0o',
    appId: '1:482880286924:android:caefb6db77a9a07c8c5269',
    messagingSenderId: '482880286924',
    projectId: 'truemedic-ef04a',
    storageBucket: 'truemedic-ef04a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35adSrNQiuQ-Sm-5jGvwNa01E3jfzWu8',
    appId: '1:482880286924:ios:e5ee7dc098a18efd8c5269',
    messagingSenderId: '482880286924',
    projectId: 'truemedic-ef04a',
    storageBucket: 'truemedic-ef04a.firebasestorage.app',
    iosBundleId: 'com.example.truemedic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB35adSrNQiuQ-Sm-5jGvwNa01E3jfzWu8',
    appId: '1:482880286924:ios:e5ee7dc098a18efd8c5269',
    messagingSenderId: '482880286924',
    projectId: 'truemedic-ef04a',
    storageBucket: 'truemedic-ef04a.firebasestorage.app',
    iosBundleId: 'com.example.truemedic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVGvHxYZRcSSpo3hamuUy76KGPtGWTOaQ',
    appId: '1:482880286924:web:42341cd6151e0e458c5269',
    messagingSenderId: '482880286924',
    projectId: 'truemedic-ef04a',
    authDomain: 'truemedic-ef04a.firebaseapp.com',
    storageBucket: 'truemedic-ef04a.firebasestorage.app',
    measurementId: 'G-H9860XZ6VT',
  );
}
